gallery/urls.py
from django.urls import path
from django.http import HttpResponse

from . import views

app_name="gallery"

urlpatterns = [
    path('', views.index.as_view(), name="index"),
    path('post/', views.CreatePostView.as_view(), name='add_post')
]

instaClone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gallery.urls')),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models

# Create your models here.

from django.db import models

class Post(models.Model):
    title = models.TextField()
    cover = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

gallery/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        title = forms.CharField(max_length=100)
        fields = ['cover', 'title']

gallery/views.py
from django.views import generic
from django.urls import reverse_lazy 
from .forms import PostForm 
from .models import Post
# Create your views here.

class index(generic.ListView):
    model = Post
    template_name="pages/index.html"

class CreatePostView(generic.CreateView): 
    model = Post
    form_class = PostForm
    template_name = 'pages/post.html'
    success_url = reverse_lazy('gallery:index')

instaClone/views.py
from django.shortcuts import render

templates/pages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}">
    <title>{% block title %} InstaClone {% endblock %}</title>
</head>
<body>
    <a class="logo" href="{% url 'gallery:index'%}"><img  src="{% static '/img/logo.png' %}"></a>

    {% block addPhoto %}{% endblock %}

    <div class="content">

        {% block content %}{% endblock %}
        
    </div>

<footer> &copy; Becode </footer>
    
</body>
</html>

templates/pages/index.html
{% extends "pages/base.html" %}
{% load static %}
{% block title %} InstaClone | Image Gallery {% endblock %}



 {% block addPhoto %}<a class="photoAdd" href="{% url 'gallery:add_post'%}"><img src="{% static '/img/addpic.png' %}"></a>{% endblock %}



{% block content %}
<ul>

  {% for post in object_list %}

  <li>

    <a href="#">
    <img src="{{ post.cover.url}}" alt="{{ post.title }}">
    </a>

    <h2>{{ post.title }}</h2>

  </li>

  {% endfor %}
</ul>


{% endblock %}

templates/pages/post.html
{% extends "pages/base.html" %}
{% load static %}

{% block content %}

<form method="post" enctype="multipart/form-data">
<h1> Ajoute une photo </h1>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">OK</button>
</form>

{% endblock %}